### ISSUE TITLE
No Sound

### ISSUE THREAD

**Issue by DQ318** [Kookpot/SuperNintendoEmulator#1]
Hello!
Great work here! I've been testing your emulator and it worked.
However, in my tests, many of the games do not start, and when they start, none of them have sound.
I'd like some help with this.
Thank you.

**Comment by Kookpot** [comment]
Hi DQ318,

Yes, the SNESFromScratch Project will work with some ROM's but only very buggy and no sound etc.
I'm working on a new emulator for the past weeks now to include sound and to work for more ROM's but it is a lot of work. Please check in a few weeks again for some updates on this.

Cheers,
Kookpot

**Comment by DQ318** [comment]
Hi, @Kookpot.

Nice!
I'm following the project as a learning tool because I'm starting to learn the C # language and found its code here by accident but I liked it too much :)

I will be following evolution. Later, would it be possible to implement things like netplay? Would it also be possible to implement some kind of scoreboard, as was done in the snes9x emulator?

Cheers!

**Comment by Kookpot** [comment]
Sound works. It took me more than 2 years :-)
